= json2bean-standalone

This is the standalone project for an dependent executable jar to run from command line to translate JSON data to schema or idl of the specific target supported.

== Build

You need Java and Maven setup properly first, then run maven command to build the executable jar ``mvn -U clean package -am -pl json2bean-standalone``.

And the jar will be in the target directory of the project.

== Download

The jar is also built and published to Maven Central.

[source,xml]
----
<dependency>
    <groupId>org.reploop</groupId>
    <artifactId>json2bean-standalone</artifactId>
    <version>${project.version}</version>
</dependency>
----

Just search and download there.
The release version is not available right now, but I am working on that.

== Run

Run `java -jar json2bean-standalone-0.17-SNAPSHOT.jar` or set an alias for that as ``alias json2="java -jar json2bean-standalone-0.17-SNAPSHOT.jar"`` for convenience.

Run ``json2`` from command line, will get the following help info

[source,bash]
----
usage: json2 <command> [ <args> ]

Commands are:
    all      Convert JSON to all supported targets in one run.
    avro     Translate JSON to Apache Avro schema.
    bean     Convert JSON to Java POJO.
    go       Translate JSON to golang struct.
    help     Display help information
    proto    Translate JSON to Protobuf Schema.
    thrift   Translate JSON to Thrift IDL.

See 'json2 help <command>' for more information on a specific command.
----

For a single command, We can check help info too by execute ``json2 help bean`` for example.

[source,bash]
----
java -jar json2bean-standalone-0.17-SNAPSHOT.jar help bean
NAME
        json2 bean - Convert JSON to Java POJO.

SYNOPSIS
        json2 bean [ {--enable-fail-fast | -ff} ] [ --enable-root-guess ]
                [ {--input | -i} <inputDirectories>... ]
                [ {--namespace | -n} <namespace> ]
                [ {--output | -o} <outputDirectory> ] [ --uri <uris>... ]

OPTIONS
        --enable-fail-fast, -ff
            Fail if any error occurred. Default true.

        --enable-root-guess
            Try to guess a reasonable root name from the filename or the API
            uri given, otherwise $ is used by default.

        --input <inputDirectories>, -i <inputDirectories>
            Process all json file in the input directory.

        --namespace <namespace>, -n <namespace>
            The top package or namespace of the source. Add package line to the
            source. Default is empty.

        --output <outputDirectory>, -o <outputDirectory>
            Where the source code should go

        --uri <uris>
            An uri to specify where the JSON is. It's schema should be file,
            http or https, we can handle each of them differently.
----

All targets' files will be in the output directory.
But for a specific target, like maven **src/main/java** or **src/main/scala**, they are in a separate directory for each target in the output directory.