# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            }]
          repositories: |
            [{
                "id": "ossrh",
                "name": "OSSRH",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
            }]
          plugin_repositories: |
            [{
                "id": "ossrh",
                "name": "OSSRH",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
            }]
      - name: Build with Maven
        run: |
          mvn -B package
        env:
          GITHUB_TOKEN: ${{ github.token }}

