# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '25' ]
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v6
        with:
          distribution: "corretto"
          java-version: ${{ matrix.java }}
          server-id: "ossrh"
          server-username-env-var: OSSRH_USERNAME
          server-password-env-var: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase-env-var: GPG_PASSPHRASE
          cache: 'maven'
          mvn-repositories-include-central: true
          mvn-repositories-prioritize-central: true
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.16
      - name: Build with Maven
        run: |
          mvn -B clean package
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}